### ISSUE TITLE
sys-info v0.5.10 broken on windows

### ISSUE THREAD

**Issue by ry** [FillZpp/sys-info-rs#50]
https://github.com/denoland/deno/pull/4270/checks?check_run_id=490557406
```
error[E0425]: cannot find function `sysconf` in crate `libc`
##[error]   --> C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\sys-info-0.5.10\lib.rs:396:34
    |
396 |             let buf_size = libc::sysconf(libc::_SC_HOST_NAME_MAX) as usize;
    |                                  ^^^^^^^ not found in `libc`

error[E0425]: cannot find value `_SC_HOST_NAME_MAX` in crate `libc`
##[error]   --> C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\sys-info-0.5.10\lib.rs:396:48
    |
396 |             let buf_size = libc::sysconf(libc::_SC_HOST_NAME_MAX) as usize;
    |                                                ^^^^^^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find function `gethostname` in crate `libc`
##[error]   --> C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\sys-info-0.5.10\lib.rs:398:22
    |
398 |             if libc::gethostname(buf.as_mut_ptr() as *mut libc::c_char, buf_size) < 0 {
    |                      ^^^^^^^^^^^ help: a function with a similar name exists: `getsockname`

```

It seems v0.5.9 was also broken https://github.com/FillZpp/sys-info-rs/issues/42

**Comment by NieDzejkob** [comment]
This is fixed already on master. @FillZpp maybe it's time for another release?

**Comment by FillZpp** [comment]
Hi @NieDzejkob @ry, sys-info `v0.6.0` has been released. Please check if it is fiexed.

**Comment by ry** [comment]
No, it is still broken on windows: https://github.com/denoland/deno/pull/4495/checks?check_run_id=536592299

I would suggest you have add windows CI.

**Comment by jclulow** [comment]
I've taken a swing at a complete fix for this in FillZpp/sys-info-rs#55, and have tested in myself in a Windows 10 VM.
